#!/bin/bash
# This script shows how to use GitHub's provided link to allow the token

echo "🔐 Allowing GitHub Token Push Method 🔐"
echo ""
echo "GitHub detected a token in your repository history that cannot be removed easily."
echo "The error message provided a direct link to allow this token for pushing:"
echo ""
echo "https://github.com/rijwanmirza/ri/security/secret-scanning/unblock-secret/2x4y9nn4Q9cruYhONcI4iS9IH5A"
echo ""
echo "INSTRUCTIONS:"
echo "1. Open the link above in your browser"
echo "2. Click 'I understand the risk, allow this secret'"
echo "3. Enter your reason (e.g., 'Token is no longer valid')"
echo "4. After allowing the token, return here and try pushing again"
echo ""
echo "Once the token is allowed, push with:"
echo "git push -f origin main"
echo ""
echo "⚠️ IMPORTANT SECURITY NOTE ⚠️"
echo "This token is now visible in your repository history."
echo "For best security practice, revoke this token immediately after pushing"
echo "and create a new token for future use."
echo ""
echo "NEXT STEPS AFTER PUSHING:"
echo "1. Go to GitHub -> Settings -> Developer settings -> Personal access tokens"
echo "2. Revoke the token: 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"
echo "3. Create a new token for future use"
echo "4. Store the new token securely, NOT in your code"
echo ""